# 安装必须要包

In [4]:
#### install third party libs
#!pip install sqlalchemy
#!pip install mysql-connector-python
!pip install pymysql
#!pip install sqlalchemy
!pip install DBUtils

import os
import pandas as pd
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 500)

import tqdm
from tqdm import tqdm
tqdm.pandas(desc='apply')
import pymysql

Requirement already satisfied: pymysql in /opt/anaconda3/lib/python3.11/site-packages (1.1.1)
Requirement already satisfied: DBUtils in /opt/anaconda3/lib/python3.11/site-packages (1.2)

# 本地mysql数据库连接

In [389]:
import pymysql

try:
    conn.close()
except:
    print('conn not exisit or close failed')
    
## 尝试关闭mysql connection
def get_mysql_connection():
    ''' try:
        conn.close()
    except Exception as e:
        print(e) 
    finally:
        print('mysql connection closed!')
        pass
    '''
    
    conn = pymysql.connect(
        host='localhost',
        port=int(3306),
        user="root",
        passwd='0921051011Liu',
        db="faers",
        charset='utf8mb4')
    
    return conn

conn = get_mysql_connection()

## mysql 数据库连接池

In [3]:
!pip install DButils==1.2
import DBUtils

Collecting DButils==1.2
  Downloading DBUtils-1.2.tar.gz (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 134.3 kB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: DButils
  Building wheel for DButils (setup.py) ... done
  Created wheel for DButils: filename=DBUtils-1.2-py3-none-any.whl size=126476 sha256=4d36e7d61f7194dd799e2cdb8f5ae134a73cbab2119953dd657cd0229211ae79
  Stored in directory: /Users/liuhaoran/Library/Caches/pip/wheels/c9/d7/41/92c5b5a10fb27b51b2b7437822390fcc8fe8ef1250fe0b4601
Successfully built DButils
Installing collected packages: DButils
  Attempting uninstall: DButils
    Found existing installation: DBUtils 3.0.3
    Uninstalling DBUtils-3.0.3:
      Successfully uninstalled DBUtils-3.0.3
Successfully installed DButils-1.2

In [390]:
import pymysql
import DBUtils
from timeit import default_timer
from DBUtils.PooledDB import PooledDB
# https://zhuanlan.zhihu.com/p/687472604

class DMysqlConfig:
    """

        :param mincached:连接池中空闲连接的初始数量
        :param maxcached:连接池中空闲连接的最大数量
        :param maxshared:共享连接的最大数量
        :param maxconnections:创建连接池的最大数量
        :param blocking:超过最大连接数量时候的表现，为True等待连接数量下降，为false直接报错处理
        :param maxusage:单个连接的最大重复使用次数
        :param setsession:optional list of SQL commands that may serve to prepare
            the session, e.g. ["set datestyle to ...", "set time zone ..."]
        :param reset:how connections should be reset when returned to the pool
            (False or None to rollback transcations started with begin(),
            True to always issue a rollback for safety's sake)
        :param host:数据库ip地址
        :param port:数据库端口
        :param db:库名
        :param user:用户名
        :param passwd:密码
        :param charset:字符编码
    """

    def __init__(self, host, db, user, password, port=3306):
        self.host = host
        self.port = port
        self.db = db
        self.user = user
        self.password = password

        #self.charset = 'UTF8'  # 不能是 utf-8
        self.minCached = 10
        self.maxCached = 20
        self.maxShared = 10
        self.maxConnection = 100

        self.blocking = True
        self.maxUsage = 100
        self.setSession = None
        self.reset = True


# ---- 用连接池来返回数据库连接
class DMysqlPoolConn:

    __pool = None

    def __init__(self, config):

        if not self.__pool:
            self.__class__.__pool = PooledDB(creator=pymysql,
                                             maxconnections=config.maxConnection,
                                             mincached=config.minCached,
                                             maxcached=config.maxCached,
                                             maxshared=config.maxShared,
                                             blocking=config.blocking,
                                             maxusage=config.maxUsage,
                                             setsession=config.setSession,
                                             #charset=config.charset,
                                             host=config.host,
                                             port=config.port,
                                             database=config.db,
                                             user=config.user,
                                             password=config.password,
                                             )

    def get_conn(self):
        return self.__pool.connection()


# ========== 在程序的开始初始化一个连接池
host = 'localhost'
port = 3306
db = 'faers'
user = 'root'
password = '0921051011Liu'
db_config = DMysqlConfig(host, db, user, password, port)
g_pool_connection = DMysqlPoolConn(db_config)
conn = g_pool_connection.get_conn()

# 基础数据检查

## 对demo表进行去重, 
sql 如下：
`DROP TABLE if exists faers.demo_dedup;
CREATE TABLE faers.demo_dedup as
SELECT
        *,
        ROW_NUMBER() OVER (PARTITION BY CASEID ORDER BY FDA_DT DESC, PRIMARYID DESC) as rn
    FROM faers.faers_demo
;`

In [ ]:
# https://www.nature.com/articles/s41598-024-58460-6
# and then PRIMARYID. For reports with the same CASEID, we retain the one with the largest FDA_DT value. Secondly, for reports where both CASEID and FDA_DT are the same,
# see faers.demo_dedup

In [6]:
import pandas as pd
df = pd.read_sql_query("select rn,count(1),count(distinct primaryid),count(distinct caseid) from faers.demo_dedup group by rn order by rn;", conn)
df

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_38268/136583447.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("select rn,count(1),count(distinct primaryid),count(distinct caseid) from faers.demo_dedup group by rn order by rn;", conn)

    rn  count(1)  count(distinct primaryid)  count(distinct caseid)
0    1  10219652                   10219652                10219652
1    2   1225829                    1225829                 1225829
2    3    262514                     262514                  262514
3    4     90825                      90825                   90825
4    5     38521                      38521                   38521
5    6     18732                      18732                   18732
6    7      9734                       9734                    9734
7    8      5281                       5281                    5281
8    9      2858                       2858                    2858
9   10      1557                       1557                    1557
10  11       830                        830                     830
11  12       438                        438                     438
12  13       240                        240                     240
13  14       129                        129                     129
14  15        63                         63                      63
15  16        27                         27                      27
16  17         8                          8                       8
17  18         4                          4                       4
18  19         1                          1                       1

In [12]:
df = pd.read_sql_query("select count(1),count(distinct primaryid),count(distinct caseid) from faers.faers_drug;", conn)
df

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_8244/4200782247.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("select count(1),count(distinct primaryid),count(distinct caseid) from faers.faers_drug;", conn)

   count(1)  count(distinct primaryid)  count(distinct caseid)
0  17223552                    4362113                 3895924

In [42]:
sql = ''' 
--   获得药品相关的所有case
DROP TABLE  if exists faers.ribo_drug_usage;
CREATE TABLE faers.ribo_drug_usage as
select *
from faers.faers_drug d1
where (lower(d1.drugname) like 'ribociclib%'
        OR lower(d1.drugname) like '%kisqali%'
        OR lower(d1.prod_ai) like '%ribociclib%'
        OR lower(d1.prod_ai) like '%kisqali%'
    ) and lower(d1.role_cod) = 'ps'
    ;

select count(1),count(distinct primaryid),count(distinct caseid) from faers.ribo_drug_usage;
 '''

df = pd.read_sql_query(sql, conn)
df.tail(10)

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_8244/2129124748.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(sql, conn)

DatabaseError: Execution failed on sql '
-- 获得药品相关的所有case
DROP TABLE  if exists faers.ribo_caseid_tb;
CREATE TABLE faers.ribo_caseid_tb as
select primaryid, caseid, DRUG_SEQ,START_DT
from faers.faers_drug d1
where (lower(d1.drugname) like 'ribociclib%'
        OR lower(d1.drugname) like '%kisqali%'
        OR lower(d1.prod_ai) like '%ribociclib%'
        OR lower(d1.prod_ai) like '%kisqali%'
    ) and lower(d1.role_cod) = 'ps'
; ': (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE faers.ribo_caseid_tb as\nselect primaryid, caseid, DRUG_SEQ,START_DT' at line 3")

In [ ]:
sql = ''' 
--   获得药品相关的所有case
DROP TABLE  if exists faers.ribo_drug_usage_retained;
CREATE TABLE faers.ribo_drug_usage_retained as
    select d3.primaryid as primaryid
    from faers.ribo_drug_usage t2
    join faers.demo_dedup d3
    on d3.rn = 1 and t2.primaryid = d3.primaryid
;'''

df_ribo = pd.read_sql_query(sql, conn)
df.tail(10)

In [39]:
sql = ''' 
    -- DROP TABLE faers.ribo_related_caseid_primary_tb;
    CREATE TABLE faers.ribo_related_caseid_primary_tb as
    select  d1.caseid, d1.primaryid
    from faers.faers_drug d1
    where (lower(d1.drugname) like 'ribociclib%'
            OR lower(d1.drugname) like '%kisqali%'
            OR lower(d1.prod_ai) like '%ribociclib%'
            OR lower(d1.prod_ai) like '%kisqali%'
        ) and caseid is not null and caseid not in ('', '0')
        and primaryid is not null and primaryid not in ('', '0')
    group by 1,2;
    '''

df = pd.read_sql_query(sql, conn)
df.tail(10)

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_61625/223975595.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(sql, conn)

TypeError: 'NoneType' object is not iterable

In [ ]:

sql = '''
SELECT  sex, COUNT(distinct tb1.caseid) AS caseid_count
FROM
(   select  primaryid, sex
    from faers.demo_dedup
    where rn = 1
) tb1
join (
        select distinct caseid
        from faers.ribo_related_caseid_primary_tb
) tb2
on tb1.caseid = tb2.caseid
group by sex;
'''

## 比较 faers.ribo_drug_usage_non_ps 和 faers.ribo_drug_usage

In [16]:
sql = ''' 
    select  t1.caseid as caseid, t1.primaryid, 
            t2.primaryid as non_ps_primaryid, t2.role_cod as non_ps_role_cod
    from (
    select caseid,primaryid
    from faers.ribo_drug_usage
    group by caseid,primaryid
    ) t1
    join 
    (
        select caseid,primaryid,role_cod
        from faers.ribo_drug_usage_non_ps
        group by caseid,primaryid,role_cod
    ) t2
    on t1.caseid = t2.caseid 
    '''
# 结论：存在这样的caseid:同时包含 PS 和 非PS作用
df = pd.read_sql_query(sql, conn)
df.tail(10)

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_61625/2390358115.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(sql, conn)

         caseid  primaryid non_ps_primaryid non_ps_role_cod
17229  23513272  235132721        235132721              SS
17230  23519209  235192091        235192091              SS
17231  23530507  235305072        235305072              SS
17232  23560238  235602384        235602384              SS
17233  23566852  235668522        235668522              SS
17234  23637234  236372341        236372341              SS
17235  23649427  236494271        236494271              SS
17236  23659698  236596981        236596981              SS
17237  23673471  236734712        236734712              SS
17238  23681982  236819821        236819821              SS

# Table1.1性别

In [ ]:
## select * from faers_reac limit

In [33]:
sql = '''

SELECT  
    case 
        when sex in ('UNK','') then  'Unknown'
        when sex = 'M' then  'Male'
        when sex = 'F' then  'Female'
        else sex
    end as sex, COUNT(distinct tb1.primaryid) AS primaryid_count
FROM
(   select  primaryid,  sex
    from faers.demo_dedup
    where rn = 1
) tb1
join (
        select distinct primaryid
        from faers.ribo_drug_usage
) tb2
on tb1.primaryid = tb2.primaryid
group by 1 order by 1;

'''
df_sex = pd.read_sql_query(sql, conn)
df_sex

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_43979/1246684853.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_sex = pd.read_sql_query(sql, conn)

       sex  primaryid_count
0   Female            13932
1     Male              269
2  Unknown             1124

In [34]:
df_sex

       sex  primaryid_count
0   Female            13932
1     Male              269
2  Unknown             1124

## 按照  性别 × outcome 统计

In [385]:
sql = '''

SELECT  
    case 
        when sex in ('UNK','') then  'Unknown'
        when sex = 'M' then  'Male'
        when sex = 'F' then  'Female'
        else sex
    end as sex,
    if(tb3.OUTC_COD is not null or tb1.primaryid in ('213797471','222788121'),'Serious cases','Non-Serious cases') as outcome,
    COUNT(distinct tb1.primaryid) AS primaryid_count
FROM
(   select  primaryid,  sex
    from faers.demo_dedup
    where rn = 1
) tb1
join (
    select distinct primaryid
    from faers.ribo_drug_usage
) tb2
on tb1.primaryid = tb2.primaryid
left join (
    select primaryid, max(OUTC_COD) as OUTC_COD
    from faers.faers_outc
    group by primaryid
) tb3 on tb1.primaryid = tb3.primaryid
group by 1,2 order by 1,2;

'''
df_sex = pd.read_sql_query(sql, conn)
df_sex

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_43979/4183436052.py:30: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_sex = pd.read_sql_query(sql, conn)

       sex            outcome  primaryid_count
0   Female  Non-Serious cases             3544
1   Female      Serious cases            10388
2     Male  Non-Serious cases               61
3     Male      Serious cases              208
4  Unknown  Non-Serious cases              441
5  Unknown      Serious cases              683

# Table1.2年龄

In [8]:
sql = '''

select
    case
            when age = '无' or cast(age as signed) < 0 then 'Unknown'
            when cast(age as signed) >= 0  and cast(age as signed) < 18 then '＜18'
            when cast(age as signed) >= 18 and cast(age as signed) < 29 then '18-29'
            when cast(age as signed) >= 30 and cast(age as signed) < 49 then '30-49'
            when cast(age as signed) >= 50 and cast(age as signed) < 64 then '50-64'
            when cast(age as signed) >= 65 and cast(age as signed) < 74 then '65-74'
            when cast(age as signed) > 75  and cast(age as signed) < 84 then '75-84'
            when cast(age as signed) > 75  and cast(age as signed) < 84 then '75-84'
            else '>=85'
    end as age_group,
    COUNT(distinct tb1.primaryid) AS primaryid_count
FROM
(
    select primaryid, age
    from faers.demo_dedup
    where rn = 1
) tb1
join (
        select distinct primaryid
        from faers.ribo_drug_usage
) tb2
on tb1.primaryid = tb2.primaryid
group by 1
order by 1
;
'''
df_age = pd.read_sql_query(sql, conn)
df_age

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_38268/1584813064.py:31: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_age = pd.read_sql_query(sql, conn)

       age  primaryid_count
0      ＜18               19
1     >=85              803
2    18-29               39
3    30-49             1391
4    50-64             2307
5    65-74             1663
6    75-84              756
7  Unknown             8347

## 年龄的分位

In [387]:
sql = '''

select 
    if(tb3.OUTC_COD is not null or tb1.primaryid in ('213797471','222788121'),'Serious cases','Non-Serious cases') as outcome,
    cast(age as signed) as age
FROM
(
    select primaryid, age
    from faers.demo_dedup
    where age not in ('Unknown','无') and cast(age as signed) >= 0
) tb1
join (
        select distinct primaryid
        from faers.ribo_drug_usage
) tb2
on tb1.primaryid = tb2.primaryid
left join (
    select primaryid, max(OUTC_COD) as OUTC_COD
    from faers.faers_outc
    group by primaryid
) tb3 on tb1.primaryid = tb3.primaryid
;
'''
df_age_q = pd.read_sql_query(sql, conn)

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_43979/4255908413.py:24: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_age_q = pd.read_sql_query(sql, conn)

In [50]:
## 计算不同 outcome 的cases的年龄均值和方差
df_age_q[df_age_q['outcome']=='Serious cases']['age'].describe()

count    8498.000000
mean       60.081078
std        13.403512
min         0.000000
25%        50.000000
50%        61.000000
75%        70.000000
max       102.000000
Name: age, dtype: float64

In [51]:
df_age_q[df_age_q['outcome']=='Non-Serious cases']['age'].describe()

count    864.000000
mean      62.180556
std       13.453143
min        3.000000
25%       54.750000
50%       63.000000
75%       71.250000
max       97.000000
Name: age, dtype: float64

In [28]:
df_age_q.describe()

               age
count  9362.000000
mean     60.274834
std      13.421144
min       0.000000
25%      51.000000
50%      61.000000
75%      70.000000
max     102.000000

# Table1.3体重

## 体重的分桶计

In [13]:
sql = '''

select
    case
            when wt in ('无','wt_convert_fail') then 'Unknown'
            when cast(wt as signed) >= 0  and cast(wt as signed) < 80 then '＜80'
            when cast(wt as signed) >= 80 and cast(wt as signed) < 100 then '80-100'
            when cast(wt as signed) >= 100 then '>100'
            else wt
    end as wt_bucket,
    COUNT(distinct tb1.primaryid) AS primaryid_count
FROM
(
    select primaryid, wt
    from faers.demo_dedup
    where rn = 1
) tb1
join (
        select distinct primaryid
        from faers.ribo_drug_usage
) tb2
on tb1.primaryid = tb2.primaryid
group by 1
order by 1
;
'''
df_wt = pd.read_sql_query(sql, conn)
df_wt

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_38268/1127711843.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_wt = pd.read_sql_query(sql, conn)

  wt_bucket  primaryid_count
0       ＜80             2231
1      >100              168
2    80-100              567
3   Unknown            12359

## 体重的分位点

In [20]:
sql = '''

select
    cast(wt as signed) as wt
FROM
(
    select primaryid, wt
    from faers.demo_dedup
    where rn = 1 and wt not in ('无','wt_convert_fail')
) tb1
join (
        select distinct primaryid
        from faers.ribo_drug_usage
) tb2
on tb1.primaryid = tb2.primaryid
-- group by 1 order by 1
;
'''
df_wt = pd.read_sql_query(sql, conn)
[df_wt.median(), df_wt.shape]

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_43979/1360289991.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_wt = pd.read_sql_query(sql, conn)

[wt    68.0
 dtype: float64,
 (2966, 1)]

In [26]:
df_wt.describe()

                wt
count  2966.000000
mean     70.199933
std      20.544317
min       1.000000
25%      58.000000
50%      68.000000
75%      79.000000
max     610.000000

# Table1.4上报者职业

In [14]:
sql = '''

select
    OCCP_COD,
    COUNT(distinct tb1.primaryid) AS primaryid_count
FROM
(
    select primaryid, OCCP_COD
    from faers.demo_dedup
    where rn = 1
) tb1
join (
        select distinct primaryid
        from faers.ribo_drug_usage
) tb2
on tb1.primaryid = tb2.primaryid
group by 1
order by 1
;
'''
df_reporter = pd.read_sql_query(sql, conn)
df_reporter

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_38268/3694848735.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_reporter = pd.read_sql_query(sql, conn)

  OCCP_COD  primaryid_count
0                       316
1       CN             8115
2       HP             1701
3       MD             3835
4       OT              792
5       PH              566

# Table1.5不良反应造成的结局

In [60]:
sql = '''

select
    OUTC_COD,
    COUNT(distinct tb1.primaryid) AS primaryid_count
FROM
(
    select primaryid, max(OUTC_COD) as OUTC_COD
    from faers.faers_outc
    group by primaryid
) tb1
join (
        select distinct primaryid
        from faers.ribo_drug_usage
) tb2
on tb1.primaryid = tb2.primaryid
join (
    select primaryid
    from faers.demo_dedup
    where rn = 1
) tb3 on tb2.primaryid = tb3.primaryid
group by 1
order by 1
;
'''
df_outcome = pd.read_sql_query(sql, conn)
df_outcome

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_38268/4220415200.py:26: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_outcome = pd.read_sql_query(sql, conn)

  OUTC_COD  primaryid_count
0        0             2036
1        1               81
2        2             1972
3        3               67
4        4                1
5        5               15
6        6             7105

In [31]:
df_outcome

  OUTC_COD  caseid_count
0        0          2034
1        1            82
2        2          1973
3        3            66
4        4             1
5        5            15
6        6          7270

# Table1.6不良反应上报的国家

               primaryid_count
continent
Africa                     339
Asia/Japan                1749
Europe                    3050
Missing                   2101
North America             6371
Oceania                    183
South America             1532

In [16]:
sql = '''

select
    REPORTER_COUNTRY,
    COUNT(distinct tb1.primaryid) AS primaryid_count
FROM
(
    select primaryid, REPORTER_COUNTRY
    from faers.demo_dedup
    where rn = 1
) tb1
join (
        select distinct primaryid
        from faers.ribo_drug_usage
) tb2
on tb1.primaryid = tb2.primaryid
group by 1
order by 1
;
'''
df_reporter_country = pd.read_sql_query(sql, conn)

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_38268/2444512671.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_reporter_country = pd.read_sql_query(sql, conn)

   REPORTER_COUNTRY  primaryid_count
0                AE               29
1                AR              348
2                AT               84
3                AU              183
4                BA                4
..              ...              ...
78               US             5683
79               UY                2
80               UZ                1
81               VN               12
82               ZA               69

[83 rows x 2 columns]

In [20]:
# https://www.cnblogs.com/pine007/p/16904126.html
def get_con_by_country_code(country):
    if country.upper() in [
        'AX', 'AL', 'AD', 'AT', 'BY', 'BE', 'BA', 'BG', 'HR', 'CZ', 'DK', 'EE', 'FO', 'FI', 'FR', 'DE', 'GI', 'GR', 'GG', 'VA', 'HU', 'IS', 'IE', 'IM', 'IT', 'JE', 'LV', 'LI', 'LT', 'LU', 'MK', 'MT', 'MD', 'MC', 'ME', 'NL', 'NO', 'PL', 'PT', 'RO', 'RU', 'SM', 'RS', 'SK', 'SI', 'ES', 'SJ', 'SE', 'CH', 'UA', 'GB']:
        return 'Europe'
    elif country.upper() in ['AF', 'AM', 'AZ', 'BH', 'BD', 'BT', 'BN', 'KH', 'CN', 'CC', 'CY', 'GE', 'HK', 'IN', 'ID', 'IR', 'IQ', 'IL', 'JP', 'JO', 'KZ', 'KP', 'KR', 'KW', 'KG', 'LA', 'LB', 'MO', 'MY', 'MV', 'MN', 'MM', 'NP', 'OM', 'PK', 'PS', 'PH', 'QA', 'SA', 'SG', 'LK', 'SY', 'TW', 'TJ', 'TH', 'TL', 'TR', 'TM', 'AE', 'UZ', 'VN', 'YE']:
        return 'Asia/Japan'
    elif country.upper() in ['DZ', 'AO', 'BJ', 'BW', 'IO', 'BF', 'BI', 'CM', 'CV', 'CF', 'TD', 'KM', 'CG', 'CD', 'CI', 'DJ', 'EG', 'GQ', 'ER', 'ET', 'TF', 'GA', 'GM', 'GH', 'GN', 'GW', 'KE', 'LS', 'LR', 'LY', 'MG', 'MW', 'ML', 'MR', 'MU', 'YT', 'MA', 'MZ', 'NA', 'NE', 'NG', 'RE', 'RW', 'SH', 'ST', 'SN', 'SC', 'SL', 'SO', 'ZA', 'SD', 'SZ', 'TZ', 'TG', 'TN', 'UG', 'EH', 'ZM', 'ZW']:
        return 'Africa'
    elif country.upper() in ['AI', 'AG', 'AW', 'BS', 'BB', 'BZ', 'BM', 'CA', 'KY', 'CR', 'CU', 'DM', 'DO', 'SV', 'GL', 'GD', 'GP', 'GT', 'HT', 'HN', 'JM', 'MQ', 'MX', 'MS', 'AN', 'NI', 'PA', 'PR', 'KN', 'LCA', 'PM', 'VC', 'TTO', 'TC', 'US', 'VG', 'VI']:
        return 'North America'
    elif country.upper() in ['AR', 'BO', 'BR', 'CL', 'CO', 'EC', 'FK', 'GF', 'GY', 'PY', 'PE', 'SR', 'UY', 'VE']:
        return 'South America'
    elif country.upper() in ['AS', 'AU', 'CX', 'CK', 'FJ', 'PF', 'GU', 'KI', 'MH', 'FM', 'NR', 'NC', 'NZ', 'NU', 'NF', 'MP', 'PW', 'PG', 'PN', 'WS', 'SB', 'TK', 'TO', 'TV', 'UM', 'VU', 'WF']:
        return 'Oceania'
    elif country.upper() in ['BV', 'HM', 'GS']:
        return 'Antarctica'
    
    return 'Missing'
        
df_reporter_country['continent'] = df_reporter_country['REPORTER_COUNTRY'].map(get_con_by_country_code)
df_reporter_country.groupby(['continent',]).sum('primaryid_count')

               primaryid_count
continent
Africa                     339
Asia/Japan                1749
Europe                    3050
Missing                   2101
North America             6371
Oceania                    183
South America             1532

# TABELe1.7 不良反应上报的pt

In [64]:
#todo：有问题
sql = '''

select
    pt,
    OUTC_COD,
    COUNT(distinct tb1.primaryid) AS primaryid_count
FROM
(
    select primaryid, max(OUTC_COD) as OUTC_COD
    from faers.faers_outc
    group by primaryid
) tb1
join (
        select distinct primaryid
        from faers.ribo_drug_usage
) tb2
on tb1.primaryid = tb2.primaryid
join (
    select primaryid
    from faers.demo_dedup
    where rn = 1
) tb3 on tb2.primaryid = tb3.primaryid
join (
    select  
            primaryid,
            concat(SOC, ':', replace(t1.pt,'\\r', '')) as pt
    from faers.faers_reac t1
) tb4 on tb3.primaryid = tb4.primaryid
group by 1
order by 1
;
'''
df_outcome_pt = pd.read_sql_query(sql, conn)
df_outcome_pt

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_43979/1987663463.py:33: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_outcome_pt = pd.read_sql_query(sql, conn)

DatabaseError: Execution failed on sql '

select
    pt,
    OUTC_COD,
    COUNT(distinct tb1.primaryid) AS primaryid_count
FROM
(
    select primaryid, max(OUTC_COD) as OUTC_COD
    from faers.faers_outc
    group by primaryid
) tb1
join (
        select distinct primaryid
        from faers.ribo_drug_usage
) tb2
on tb1.primaryid = tb2.primaryid
join (
    select primaryid
    from faers.demo_dedup
    where rn = 1
) tb3 on tb2.primaryid = tb3.primaryid
join (
    select
            primaryid,
            concat(SOC, ':', replace(t1.pt,'\r', '')) as pt
    from faers.faers_reac t1
) tb4 on tb3.primaryid = tb4.primaryid
group by 1
order by 1
;
': (1055, "Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'tb1.OUTC_COD' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")

## Time of onset

In [ ]:
## drug usage show

In [45]:
## DROP TABLE  if exists faers.drug_usage_with_ae;

sql ='''
-- DROP TABLE  if exists faers.drug_usage_with_ae;
CREATE TABLE  faers.drug_usage_with_ae  as
SELECT 
    D.CASEID,
    D.PRIMARYID,
    R.DRUG_SEQ,
    -- 至少6位
    if(length(T.START_DT) >= 6, rpad(T.START_DT, 8, '01'), T.START_DT) as START_DT,
    -- 去掉 .0
    if(length(D.EVENT_DT) < 6, D.EVENT_DT,
        rpad(cast(cast(SUBSTRING_INDEX(D.EVENT_DT,'.',1) as signed) as char),8,'01')
      ) as EVENT_DT,
    T.PRIMARYID as ther_primaryid,
    T.DSG_DRUG_SEQ as ther_DSG_DRUG_SEQ
FROM  faers.demo_dedup D 
JOIN  faers.ribo_drug_usage R    -- 该份报告记录了 ribocilicib
    on D.rn = 1 and D.PRIMARYID = R.PRIMARYID        
left JOIN (
    select PRIMARYID,DSG_DRUG_SEQ,min(START_DT) as START_DT
    from faers.faers_ther 
    group by 1,2
) T ON T.PRIMARYID = R.PRIMARYID and T.DSG_DRUG_SEQ = R.DRUG_SEQ;   
-- WHERE T.START_DT IS NOT NULL  AND D.EVENT_DT IS NOT NULL;
'''

df_time_onset = pd.read_sql_query(sql, conn)
df_time_onset

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_38268/3993848341.py:29: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_time_onset = pd.read_sql_query(sql, conn)

TypeError: 'NoneType' object is not iterable

In [59]:
sql = '''
    
    select 
        case 
            when TIMESTAMPDIFF(DAY, START_DT, EVENT_DT) between 0 and 30 then '0-30 days'
            when TIMESTAMPDIFF(DAY, START_DT, EVENT_DT) between 31 and 60 then '31-60 days'
            when TIMESTAMPDIFF(DAY, START_DT, EVENT_DT) between 61 and 90 then '61-90 days'
            when TIMESTAMPDIFF(DAY, START_DT, EVENT_DT) between 91 and 180 then '91-180 days'
            when TIMESTAMPDIFF(DAY, START_DT, EVENT_DT) between 181 and 360 then '181-360 days'
            when TIMESTAMPDIFF(DAY, START_DT, EVENT_DT) > 360  then '>360 days'
        else -1 end as time_of_onset,
        count(distinct primaryid) as primaryid_count,
        count(distinct caseid) as caseid_count,
        count(1)
    from faers.drug_usage_with_ae
    where START_DT IS NOT NULL AND EVENT_DT IS NOT NULL
    group by 1 order by 1
    ;
'''
df_time_onset = pd.read_sql_query(sql, conn)
df_time_onset

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_38268/307994975.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_time_onset = pd.read_sql_query(sql, conn)

  time_of_onset  primaryid_count  caseid_count  count(1)
0            -1             2544          2544      2544
1     >360 days             1045          1045      1045
2     0-30 days             2008          2008      2008
3  181-360 days              730           730       730
4    31-60 days              652           652       652
5    61-90 days              458           458       458
6   90-180 days              745           745       745

In [56]:
df_time_onset[df_time_onset.apply(lambda x: x['time_of_onset'] is not null and not x['time_of_onset'].startswith('-'))]

KeyError: 'time_of_onset'

In [57]:
df_time_onset

    time_of_onset  primaryid_count  caseid_count  count(1)
0            None             2077          2077      2077
1              -1               36            36        36
2             -10                6             6         6
3             -11                7             7         7
4            -115                1             1         1
..            ...              ...           ...       ...
99             73                2             2         2
100             8              121           121       121
101             9              109           109       109
102            94                1             1         1
103   Unknown_dur             7143          7143      7143

[104 rows x 4 columns]

# Table1.8上报年份

In [38]:
##  REPT_DT 存在异常数据, 否则取：INIT_FDA_DT
sql =''' 
    SELECT
        YEAR(if(length(D.REPT_DT)<4, D.INIT_FDA_DT,D.REPT_DT)) AS report_year,
        COUNT(distinct D.PRIMARYID) AS report_count
    FROM
        faers.demo_dedup D
    JOIN 
        faers.ribo_drug_usage R
    ON D.rn = 1 and D.PRIMARYID = R.PRIMARYID
    GROUP BY
        1
    ORDER BY
        1;
'''

df_rpt_year = pd.read_sql_query(sql, conn)
df_rpt_year

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_38268/2273248669.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_rpt_year = pd.read_sql_query(sql, conn)

   report_year  report_count
0         2017           473
1         2018          1161
2         2019          1575
3         2020          1490
4         2021          2222
5         2022          2958
6         2023          4547
7         2024           899

# Table2 适应症及同用药品

## 联用药物

In [43]:
# 同一个primaryid下
sql = '''

    SELECT 
        concat(d1.prod_ai) as drug_info,
        COUNT(d1.CASEID) AS concomitant_medications_caseid_count,
        COUNT(d1.primaryid) AS concomitant_medications_primaryid_count
    FROM 
          faers.faers_drug d1
    join  faers.ribo_drug_usage  d2
        on d1.primaryid = d2.primaryid and  d1.caseid = d2.caseid
    join  faers.demo_dedup d3 
        on d3.rn = 1 and d1.primaryid = d3.primaryid and  d1.caseid = d3.caseid
    where lower(d1.role_cod) != 'ps' and d1.drug_seq != d2.drug_seq
    group by 1
    order by 2 desc
    ;
'''
df_concomitant = pd.read_sql_query(sql, conn)
df_concomitant

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_38268/2949103587.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_concomitant = pd.read_sql_query(sql, conn)

,drug_info,concomitant_medications_caseid_count,concomitant_medications_primaryid_count
0,RIBOCICLIB,8757,8757
1,LETROZOLE,3990,3990
2,FULVESTRANT,1474,1474
3,,1439,1439
4,ANASTROZOLE,608,608
...,...,...,...
1198,LEVAMISOLE,1,1
1199,CORTICOTROPIN,1,1
1200,BRIVARACETAM,1,1
1201,INDAPAMIDEPERINDOPRIL ERBUMINE,1,1
1202,ALBENDAZOLE,1,1

In [46]:
len(df_concomitant)

3566

## 适应症

In [64]:
# 同一个primaryid下
# todo: INDI_PT 格式较为混乱，需要继续处理
sql = '''
    SELECT 
        replace(coalesce(d1.INDI_PT,'not_found_pt'),'\\r', '') as INDI_PT,
        COUNT(d1.CASEID) AS INDI_PT_caseid_count,
        COUNT(d1.primaryid) AS INDI_PT_primaryid_count
    FROM 
        faers.faers_indi d1
    join faers.ribo_drug_usage  d2
    on d1.primaryid = d2.primaryid 
        and d1.INDI_DRUG_SEQ = d2.drug_seq
    join  faers.demo_dedup d3 
        on d3.rn = 1 and d1.primaryid = d3.primaryid
    group by 1
    order by 2 desc
    ;
'''
df_indi = pd.read_sql_query(sql, conn)
df_indi

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_38268/139086257.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_indi = pd.read_sql_query(sql, conn)

,INDI_PT,INDI_PT_caseid_count,INDI_PT_primaryid_count
0,Product used for unknown indication,4713,4713
1,Breast cancer metastatic,4422,4422
2,Breast cancer,3955,3955
3,Hormone receptor positive HER2 negative breast...,502,502
4,Breast cancer female,500,500
...,...,...,...
159,Thrombocytopenia,1,1
160,Mesothelioma,1,1
161,Hypothyroidism,1,1
162,Gastrointestinal stromal tumour,1,1
163,Diarrhoea,1,1

In [54]:
sum(df_indi['concomitant_medications_primaryid_count'])

19801

#  Table 3,4,5 ROR分析数据准备

## 导出 和 ribociclib 相关的 pt

In [25]:
# 去除异常字符
sql = '''   
   SELECT 
        replace(coalesce(t2.pt,'not_found_pt'),'\\r', '') as pt,
        COUNT(distinct t1.CASEID) AS caseid_cnt,
        COUNT(distinct t1.PRIMARYID) AS primaryid_cnt
    FROM faers.ribo_drug_usage t1
    left join faers.faers_reac t2
    on t1.primaryid = t2.primaryid and lower(t1.role_cod) = 'ps'
    group by 1
    order by 1;
'''
df_pt_stat = pd.read_sql_query(sql, conn)

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_24540/1334817465.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_pt_stat = pd.read_sql_query(sql, conn)

KeyError: False

In [31]:
len(df_pt_stat.pt)

3223

## 并查找其 smq 和 pt

In [37]:
df_pt_stat.to_csv('ribo_pt.csv', index=False)

## 获取相关pt 到 smq & soc的映射

In [34]:
import os
import sys
import requests
from cachetools import cached, TTLCache
import time
import pandas as pd
import tqdm
g_token=''

@cached(cache=TTLCache(maxsize=1, ttl=36000))
def get_token():
    # step 1:  using username='30007'  password='2A4nFXhP' on https://mid.meddra.org/account/register for apikey
    # step 2:  apply for grant
    cmd = '''
    curl \
        --request POST \
        --data "grant_type=password"  \
        --data "username={username}"  --data "password={apikey}" \
        --data "scope=meddraapi" \
        --data "client_id=mspclient" \
        "https://mid.meddra.org/connect/token"
    '''.format(username='30007', apikey='4Lj68iPSy3jjti7hK2hM')
    os.system(cmd)
    # ref: https://cloud.tencent.com/developer/article/1908468
    return auth['access_token']
    # {"access_token":"6acb65aaaa2eee65530de8e2521606b10051a5b8a5451bdf1227eb704bda080d","expires_in":36000,"token_type":"Bearer"}

def get_token2():
    return "0ee4891cc555c08327623cf1e37697aca59bba27744b0006e138d2f0e6a47fc7"

def get_soc(row):
    ## (1) search pt name for pt-code
    headers = {
        'accept': 'application/json',
        'Authorization': 'Bearer {}'.format(get_token2()),
        'Content-Type': 'text/json',
    }

    pt_name = row['pt']   # "heart valve operation"

    data = '{"bview":"SOC","rsview":"release","language":"English","stype":1,"addlangs":[],"filters":[],"version":24,"searchterms":[{"searchtype":0,"searchterm":"' \
           + pt_name + '","searchlogic":0}],"kana":false,"idiacritical":true,"synonym":false,"contains":false,"soc":false,"hlgt":false,"hlt":false,"pt":true,"llt":false,"smq":false,"skip":0,"take":0,"separator":2}'
    
    try:
        response = requests.post('https://gxpmapiprod.meddra.org/api/search', headers=headers, data=data)
        #print(response.json())
        ##(2) detail: search soc name & code using pt_code
        pt_code = response.json()[0]['pcode']
    
        data = '{"bview":"SOC","rsview":"release","code":' + str(pt_code) + \
               ',"pcode":0,"syncode":0,"lltcode":0,"ptcode":0,"hltcode":0,"hlgtcode":0,"soccode":0,"smqcode":0,"type":"PT","addlangs":[],"rtype":"P","lang":"English","ver":24,"kana":false,"separator":2}'
    
        response = requests.post('https://gxpmapiprod.meddra.org/api/detail', headers=headers, data=data)
        soc_name = ''
        soc_code = -1
    
        for item in response.json()['mds']:
            #print(item)
            if item['primarysocfg'] == 'Y':
                soc_name = item['socname']
                soc_code = item['soccode']
                           
        ## finally output results using dataframes
        #return {'pt': pt_name, 'pt_code': pt_code, 'soc_name': soc_name, 'soc_code': soc_code}
        return pd.Series([pt_name, pt_code, soc_name, soc_code], index=['pt_name', 'pt_code', 'soc_name', 'soc_code'])

    except Exception as e:
        print("error for" + pt_name)
    finally:
        pass

In [23]:
get_token()

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0

{"access_token":"0ee4891cc555c08327623cf1e37697aca59bba27744b0006e138d2f0e6a47fc7","expires_in":36000,"token_type":"Bearer"}

100   224    0   124  100   100     65     52  0:00:01  0:00:01 --:--:--   117

NameError: name 'auth' is not defined

In [35]:
import tqdm
from tqdm import tqdm
tqdm.pandas(desc='apply')
pt_soc_mapping = df_pt_stat.progress_apply(get_soc, axis=1)

apply:   1%|          | 39/3223 [01:29<2:02:27,  2.31s/it]

KeyboardInterrupt:

In [98]:
pt_soc_mapping

                      pt_name   pt_code                     soc_name  soc_code
0         abdominal adhesions  10000050   Gastrointestinal disorders  10017947
1        abdominal discomfort  10000059   Gastrointestinal disorders  10017947
2        abdominal distension  10000060   Gastrointestinal disorders  10017947
3            abdominal hernia  10060954   Gastrointestinal disorders  10017947
4  abdominal hernia infection  10077232  Infections and infestations  10021881

In [ ]:
# 一个primaryid 
# check select count(1),count(distinct caseid),count(distinct primaryid) from faers_reac;

sql = '''

    SELECT 
        concat(d1.INDI_PT) as INDI_PT,
        COUNT(d1.CASEID) AS INDI_PT_caseid_count,
        COUNT(d1.primaryid) AS INDI_PT_primaryid_count
    FROM 
        faers.faers_reac d1
    join faers.ribo_drug_usage  d2
    on d1.primaryid = d2.primaryid 
        and d1.INDI_DRUG_SEQ = d2.drug_seq
    group by 1
    order by 1
    ;
'''
df_indi = pd.read_sql_query(sql, conn)
df_indi

In [ ]:
# faers.faers_reac:    PRIMARYID,CASEID,PT, SOC_NAME

## 计算ror矩阵中的 a,b,c,d

In [21]:
ALTER table faers.ror_pt_a_b  modify drug varchar(255) character set utf8mb3 collate utf8mb3_bin;

0

In [ ]:
sql = '''   
      DROP TABLE  if exists faers.ror_stats;
      CREATE TABLE faers.ror_stats as
      select t1.drug, t1.pt, 
             t1.drug_event_cnt,  
             coalesce(t2.drug_cnt,0) - t1.drug_event_cnt as drug_otherevent_cnt
      from faers.ror_pt_a_b t1
      left join faers.ror_pt_D_d t2
      on t1.drug = t2.drug
      ;
'''
df_ror_stats = pd.read_sql_query(sql, conn)

In [ ]:
sql = '''   
      DROP TABLE  if exists faers.ror_stats;
      CREATE TABLE faers.ror_stats as
      select t1.drug, t1.pt, 
             t1.drug_event_cnt,  
             coalesce(t2.drug_cnt,0) - t1.drug_event_cnt as drug_otherevent_cnt
      from faers.ror_pt_a_b t1
      left join faers.ror_pt_D_d t2
      on t1.drug = t2.drug
      ;
'''
df_ror_stats = pd.read_sql_query(sql, conn)

In [ ]:
## generation: pt, a,b,c,d
sql = '''   
      DROP TABLE  if exists faers.ror_pt_stats;
      CREATE TABLE faers.ror_pt_stats as
      select t1.drug, t1.pt, 
             t1.drug_event_cnt,  
             coalesce(t2.drug_cnt,0) - t1.drug_event_cnt as drug_otherevent_cnt
      from faers.ror_pt_a_b t1
      left join faers.ror_pt_D_d t2
      on t1.drug = t2.drug
      ;
'''
df_ror_pt_stats = pd.read_sql_query(sql, conn)

In [ ]:
## generation: pt, a,b,c,d
sql = '''   
      DROP TABLE  if exists faers.ror_pt_abcd;
      CREATE TABLE faers.ror_pt_abcd as
      
      select pt, drug_event_cnt as DE, 0 as dE,  drug_otherevent_cnt as De, 0 as de
          from faers.ror_pt_stats where drug = 'D'
          
      union all 
    
      select pt, 0 as DE, drug_event_cnt as dE, 0  as De, drug_otherevent_cnt as de
          from faers.ror_pt_stats where drug = 'd'
        
      ;
'''
df_ror_pt_abcd = pd.read_sql_query(sql, conn)

# TABLE 3,4,5 指标计算

## python指标算子

In [40]:
import math
# 定义相关指标的计算 python函数
## https://www.jianshu.com/p/69dfbcceef9b
def get_ROR(row):
    import math
    a = row['DE']
    b = row['De']
    c = row['dE']
    d = row['de']    
    ror = a/c/(b/d)
    ci_lower = math.log(ror) - 1.96 * math.sqrt(1/a + 1/b + 1/c + 1/d)
    ci_upper = math.log(ror) + 1.96 * math.sqrt(1/a + 1/b + 1/c + 1/d)
    return a/c/(b/d), math.exp(ci_lower), math.exp(ci_upper)

def get_PRR(row):

    a = row['DE']
    b = row['De']
    c = row['dE']
    d = row['de']    
    prr = a/(a+b)/(c/(c+d))
    ci_lower = math.log(prr) - 1.96 * math.sqrt(1/a - 1/(a+b) + 1/c - 1/(c+d))
    ci_upper = math.log(prr) + 1.96 * math.sqrt(1/a - 1/(a+b) + 1/c - 1/(c+d))
    return prr, math.exp(ci_lower), math.exp(ci_upper)

def get_MHRA(row):

    a = row['DE']
    b = row['De']
    c = row['dE']
    d = row['de']    
    
    chi_squared = math.pow( (a*d - b*c), 2) * (a+b+c+d) / ((a+b)*(c+d)*(a+c)*(b+d))
    return chi_squared


def get_EBGM(row):

    a = row['DE']
    b = row['De']
    c = row['dE']
    d = row['de']    
    
    EBGM = a*(a+b+c+d)/(a+b)/(a+c)
    ci_lower = math.log(EBGM) - 1.96 * math.sqrt(1/a + 1/b + 1/c + 1/d)
    ci_upper = math.log(EBGM) + 1.96 * math.sqrt(1/a + 1/b + 1/c + 1/d)
    
    return EBGM,  math.exp(ci_lower), math.exp(ci_upper)

In [70]:
## reads: pt, a,b,c,d
sql = '''   
      select * from faers.ror_pt_abcd where a>0;
'''
df_ror_pt_abcd = pd.read_sql_query(sql, conn)

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_24540/305480428.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ror_pt_abcd = pd.read_sql_query(sql, conn)

In [42]:
df_ror_pt_abcd.to_excel('pt_abcd.xlsx', index=False)

In [45]:
df_ror_pt_abcd.head()

                           pt      a         b        c           d
0         abdominal adhesions    2.0    1912.0  20157.0  11855172.0
1        abdominal discomfort  555.0  114630.0  19604.0  11742454.0
2        abdominal distension  216.0   60888.0  19943.0  11796196.0
3            abdominal hernia    6.0    3160.0  20153.0  11853924.0
4  abdominal hernia infection    1.0      36.0  20158.0  11857048.0

## PT 维度多重指标计算（最新）

In [398]:
import math
# 定义相关指标的计算 python函数
## https://www.jianshu.com/p/69dfbcceef9b
def get_ROR(row):
    import math

    a = row['a']
    b = row['b']
    c = row['c']
    d = row['d']
    
    if a*b*c*d == 0:
        return -1,-1,-1
    
    ror = a/c/(b/d)
    ci_lower = math.log(ror) - 1.96 * math.sqrt(1/a + 1/b + 1/c + 1/d)
    ci_upper = math.log(ror) + 1.96 * math.sqrt(1/a + 1/b + 1/c + 1/d)
    return a/c/(b/d), math.exp(ci_lower), math.exp(ci_upper)

def get_PRR(row):

    a = row['a']
    b = row['b']
    c = row['c']
    d = row['d']    
    
    if a * (a+b) * (c+d) * (b+d) * (a+c) * c == 0:
        return -1,-1,-1,-1
    
    
    prr = a/(a+b)/(c/(c+d))
    ci_lower = math.log(prr) - 1.96 * math.sqrt(1/a - 1/(a+b) + 1/c - 1/(c+d))
    ci_upper = math.log(prr) + 1.96 * math.sqrt(1/a - 1/(a+b) + 1/c - 1/(c+d))
    chi_squared = math.pow( (a*d - b*c), 2) * (a+b+c+d) / ((a+b)*(c+d)*(a+c)*(b+d))  # get_MHRA

    return prr, math.exp(ci_lower), math.exp(ci_upper),chi_squared

def get_BCPNN(row):

    a = row['a']
    b = row['b']
    c = row['c']
    d = row['d'] 
    
    C = a+b+c+d
    Cx = a + b
    Cy = a + c
    Cxy = a
    
    α1 = 1
    β1 = 1
    α = 2
    β = 2 ## modified from 1
    γ11 = 1
    
    if True: 
        γ = γ11 * (C + α) * ( C + β) / (Cx + α1) / (Cy + β1)  
        ## IC modified
        IC = math.log2(a*(a+b+c+d)/((a+c)*(a+b)))
        E_IC = math.log2( (Cxy+γ11) * (C+α) * (C+β) / (C+γ) / (Cx+α1) / (Cy+β1) )
        V_IC = ( (C-Cxy+γ-γ11)/(Cxy+γ11)/(1+C+γ) + (C-Cx+α-α1)/(Cx+α1)/(1+C+α) + (C-Cy+β-β1)/(Cy+β1)/(1+C+β) ) / (math.log(2) * math.log(2))
        CI_lower = E_IC - 2 * math.sqrt(V_IC)
        CI_upper = E_IC + 2 * math.sqrt(V_IC)
               
        return IC, E_IC, V_IC, CI_lower, CI_upper
    
    #except Exception as e:
    #    print('error for {}'.format(row))
    #    return -1,-1,-1,-1,-1
    #finally:
    #    pass

def get_MPGS(row):

    a = row['a']
    b = row['b']
    c = row['c']
    d = row['d']    
    
    if a*b*c*d*(a+c)*(a+b) == 0:
        return -1,-1,-1
    
    EBGM = a*(a+b+c+d)/(a+c)/(a+b)
    ci_lower = math.log(EBGM) - 1.96 * math.sqrt(1/a + 1/b + 1/c + 1/d)
    ci_upper = math.log(EBGM) + 1.96 * math.sqrt(1/a + 1/b + 1/c + 1/d)
    
    return EBGM,  math.exp(ci_lower), math.exp(ci_upper)

### faers.ror_pt_abcd:见 pt_analysis.sql
sql = '''   
      select * from faers.ror_pt_abcd where a>0;
'''

df_ror_pt_abcd = pd.read_sql_query(sql, conn)


df_ror_pt_abcd[["ROR", "ROR_95%CI_lower", "ROR_95%CI_upper"]] =  df_ror_pt_abcd.apply(get_ROR, axis = 1, result_type = "expand")
df_ror_pt_abcd[["PRR", "PRR_95%CI_lower", "PRR_95%CI_upper", "χ2"]] =  df_ror_pt_abcd.apply(get_PRR, axis = 1, result_type = "expand")
df_ror_pt_abcd[["BCPNN_IC","BCPNN_E(IC)", "BCPNN_V(IC)", "BCPNN_CI_lower", "BCPNN_CI_upper"]] =  df_ror_pt_abcd.apply(get_BCPNN, axis = 1, result_type = "expand")
df_ror_pt_abcd[["EBGM", "EBGM_CI_lower", "EBGM_CI_upper"]] =  df_ror_pt_abcd.apply(get_MPGS, axis = 1, result_type = "expand")
df_ror_pt_abcd.to_excel('pt_ror_result.xlsx', index=False)
#os.system('open pt_ror_result.xlsx')


###################   SOC维度指标  #################################
sql = '''   
      select * from faers.ror_soc_abcd where a>0;
'''

df_ror_soc_abcd = pd.read_sql_query(sql, conn)
df_ror_soc_abcd[["ROR", "ROR_95%CI_lower", "ROR_95%CI_upper"]] =  df_ror_soc_abcd.apply(get_ROR, axis = 1, result_type = "expand")
df_ror_soc_abcd[["PRR", "PRR_95%CI_lower", "PRR_95%CI_upper", "χ2"]] =  df_ror_soc_abcd.apply(get_PRR, axis = 1, result_type = "expand")
df_ror_soc_abcd[["BCPNN_IC","BCPNN_E(IC)", "BCPNN_V(IC)", "BCPNN_CI_lower", "BCPNN_CI_upper"]] =  df_ror_soc_abcd.apply(get_BCPNN, axis = 1, result_type = "expand")
df_ror_soc_abcd[["EBGM", "EBGM_CI_lower", "EBGM_CI_upper"]] =  df_ror_soc_abcd.apply(get_MPGS, axis = 1, result_type = "expand")
df_ror_soc_abcd.to_excel('soc_ror_result.xlsx', index=False)
#os.system('open soc_ror_result.xlsx')

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_43979/2308176122.py:94: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ror_pt_abcd = pd.read_sql_query(sql, conn)

0

In [55]:
df_ror_pt_abcd

,pt,a,b,c,d,ROR,ROR_95%CI_lower,ROR_95%CI_upper,PRR,PRR_95%CI_lower,PRR_95%CI_upper,χ2,BCPNN_IC,BCPNN_E(IC),BCPNN_V(IC),BCPNN_CI_lower,BCPNN_CI_upper,EBGM,EBGM_CI_lower,EBGM_CI_upper
0,Blood and lymphatic system disorders:abdominal...,1.0,680.0,15324.0,11861238.0,1.138280,0.160095,8.093188,1.138077,0.160528,8.068471,0.016773,46.816807,0.089244,1.043872,-1.954156,2.132645,1.138068,0.160065,8.091680
1,Blood and lymphatic system disorders:agranuloc...,6.0,9787.0,15319.0,11852131.0,0.474316,0.213003,1.056210,0.474638,0.213252,1.056409,3.492181,53.247794,-0.962189,0.297686,-2.053402,0.129023,0.474844,0.213240,1.057385
2,Blood and lymphatic system disorders:anaemia,443.0,109538.0,14882.0,11752380.0,3.193769,2.905241,3.510951,3.184932,2.898286,3.499928,645.655706,62.943354,1.635381,0.004842,1.496213,1.774550,3.121772,2.839749,3.431805
3,Blood and lymphatic system disorders:anaemia f...,1.0,129.0,15324.0,11861789.0,6.000512,0.838785,42.926566,5.962047,0.846117,42.010726,4.134840,44.427664,0.774678,1.056708,-1.281248,2.830604,5.961723,0.833363,42.649075
4,Blood and lymphatic system disorders:anaemia m...,4.0,1138.0,15321.0,11860780.0,2.721096,1.019371,7.263657,2.715068,1.020616,7.222687,4.337997,49.562643,1.014564,0.418230,-0.278850,2.307979,2.714620,1.016945,7.246370
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3164,Vascular disorders:venous thrombosis,3.0,2006.0,15322.0,11859912.0,1.157594,0.372984,3.592711,1.157359,0.373540,3.585911,0.064256,49.962520,0.154555,0.521513,-1.289762,1.598873,1.157328,0.372898,3.591885
3165,Vascular disorders:venous thrombosis limb,3.0,1264.0,15322.0,11860654.0,1.837246,0.591679,5.704910,1.835264,0.592628,5.683487,1.141684,49.297459,0.601549,0.522119,-0.843608,2.046705,1.835100,0.590988,5.698247
3166,Vascular disorders:visceral congestion,1.0,368.0,15324.0,11861550.0,2.103398,0.295475,14.973461,2.100408,0.296628,14.872857,0.577213,45.932773,0.436905,1.046445,-1.609013,2.482823,2.100336,0.295045,14.951663
3167,Gastrointestinal disorders:benign pancreatic h...,1.0,0.0,15324.0,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,27.807199,-0.584837,2.081029,-3.469992,2.300318,-1.000000,-1.000000,-1.000000
3168,"Neoplasms benign, malignant and unspecified (i...",1.0,0.0,15324.0,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,27.807199,-0.584837,2.081029,-3.469992,2.300318,-1.000000,-1.000000,-1.000000

## SOC 维度统计表格

In [399]:
sql = '''   
      select * from faers.ror_soc_abcd where a>0;
'''

df_ror_soc_abcd = pd.read_sql_query(sql, conn)


df_ror_soc_abcd[["ROR", "ROR_95%CI_lower", "ROR_95%CI_upper"]] =  df_ror_soc_abcd.apply(get_ROR, axis = 1, result_type = "expand")
df_ror_soc_abcd[["PRR", "PRR_95%CI_lower", "PRR_95%CI_upper", "χ2"]] =  df_ror_soc_abcd.apply(get_PRR, axis = 1, result_type = "expand")
df_ror_soc_abcd[["BCPNN_IC","BCPNN_E(IC)", "BCPNN_V(IC)", "BCPNN_CI_lower", "BCPNN_CI_upper"]] =  df_ror_soc_abcd.apply(get_BCPNN, axis = 1, result_type = "expand")
df_ror_soc_abcd[["EBGM", "EBGM_CI_lower", "EBGM_CI_upper"]] =  df_ror_soc_abcd.apply(get_MPGS, axis = 1, result_type = "expand")
df_ror_soc_abcd.to_excel('soc_ror_result.xlsx', index=False)
os.system('open soc_ror_result.xlsx')

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_43979/2401172928.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ror_soc_abcd = pd.read_sql_query(sql, conn)

0

In [356]:
df_ror_soc_abcd.head()

,soc,a,b,c,d,ROR,ROR_95%CI_lower,ROR_95%CI_upper,PRR,PRR_95%CI_lower,PRR_95%CI_upper,χ2,BCPNN_IC,BCPNN_E(IC),BCPNN_V(IC),BCPNN_CI_lower,BCPNN_CI_upper,EBGM,EBGM_CI_lower,EBGM_CI_upper
0,Blood and lymphatic system disorders,2023.0,444035.0,13302.0,11417883.0,3.910635,3.731575,4.098288,3.897435,3.719692,4.083671,3787.228901,67.154448,1.811618,0.001168,1.743257,1.879978,3.514955,3.354012,3.683620
1,Cardiac disorders,1122.0,557351.0,14203.0,11304567.0,1.602278,1.507701,1.702789,1.601068,1.506741,1.701300,234.947496,66.628281,0.638014,0.001992,0.548742,0.727287,1.557062,1.465153,1.654736
2,"Congenital, familial and genetic disorders",53.0,8325.0,15272.0,11853593.0,4.941351,3.770059,6.476544,4.916418,3.757443,6.432875,164.991391,56.165607,2.192709,0.038928,1.798107,2.587310,4.902873,3.740702,6.426112
3,Ear and labyrinth disorders,167.0,138062.0,15158.0,11723856.0,0.935558,0.803156,1.089788,0.935636,0.803371,1.089678,0.732310,61.865701,-0.094456,0.012539,-0.318415,0.129503,0.936338,0.803825,1.090696
4,Endocrine disorders,84.0,55162.0,15241.0,11806756.0,1.179659,0.951819,1.462037,1.179386,0.951909,1.461222,2.282298,59.551196,0.233689,0.024660,-0.080379,0.547757,1.178402,0.950806,1.460479

In [60]:
pt_outcom_stat_query = '''  
    select
        concat(SOC, ':', replace(t1.pt,'\\r', '')) as pt,
        count(distinct if(t3.OUTC_COD is not null or t1.primaryid in ('213797471','222788121'), t1.primaryid,null)) as serious_count,
        count(distinct if(t3.OUTC_COD is null and t1.primaryid not in ('213797471','222788121'),t1.primaryid,null))  as non_serious_count
    from faers.faers_reac t1
    join faers.ribo_drug_usage_retained t2  
        on t1.primaryid = t2.primaryid
    left join (
        select primaryid, max(OUTC_COD) as OUTC_COD
        from faers.faers_outc
        group by primaryid
    ) t3 
        on t1.primaryid = t3.primaryid
    Group by 1
;
''' 
df_pt_outcom_stat_query = pd.read_sql_query(pt_outcom_stat_query, conn)

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_43979/2923893240.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_pt_outcom_stat_query = pd.read_sql_query(pt_outcom_stat_query, conn)

In [73]:
df_pt_outcom_stat_query

,pt,serious_count,non_serious_count
0,Blood and lymphatic system disorders:abdominal...,1,0
1,Blood and lymphatic system disorders:agranuloc...,6,0
2,Blood and lymphatic system disorders:anaemia,411,32
3,Blood and lymphatic system disorders:anaemia f...,0,1
4,Blood and lymphatic system disorders:anaemia m...,3,1
...,...,...,...
3164,Vascular disorders:vena cava thrombosis,4,0
3165,Vascular disorders:venous occlusion,5,0
3166,Vascular disorders:venous thrombosis,3,0
3167,Vascular disorders:venous thrombosis limb,3,0
3168,Vascular disorders:visceral congestion,1,0

In [355]:
## pt_characteristics_stat数据  primaryid * pt
pt_characteristics_stat_query = '''  
    select
        t1.primaryid
        ,concat(SOC, ':', replace(t1.pt,'\\r', '')) as soc_pt
        ,replace(t1.pt,'\\r', '') as pt
        ,coalesce(t4.sex,'unknown_sex') as sex
        ,if(age = '无' or cast(age as signed) < 0,  -1, cast(age as signed)) as age
        ,if(t3.OUTC_COD is not null or lower(t1.pt) = 'death', 1, 0) as is_serious_case
        ,if((t3.OUTC_COD is not null and t3.OUTC_COD = 0) or lower(t1.pt) = 'death' ,1,0) as is_death_case
    from faers.faers_reac t1
    join faers.ribo_drug_usage_retained t2
        on t1.primaryid = t2.primaryid
    left join (
        select primaryid, min(OUTC_COD) as OUTC_COD  
        from faers.faers_outc
        group by primaryid
    ) t3 
        on t1.primaryid = t3.primaryid
    left join (  -- sex 
        select  primaryid, sex, age
        from faers.demo_dedup
        where rn = 1
    ) t4 on t1.primaryid = t4.primaryid
;
''' 
pt_characteristics_stat = pd.read_sql_query(pt_characteristics_stat_query, conn)

/var/folders/7w/sgw5xk457ss20939d0n2_5600000gn/T/ipykernel_43979/1261298582.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pt_characteristics_stat = pd.read_sql_query(pt_characteristics_stat_query, conn)

In [372]:
pt_characteristics_stat[ pt_characteristics_stat['pt']=='death']

,primaryid,soc_pt,pt,sex,age,is_serious_case,is_death_case
45,162395551,General disorders and administration site cond...,death,F,-1,1,1
46,163345021,General disorders and administration site cond...,death,F,33,1,1
65,170609081,General disorders and administration site cond...,death,F,73,1,1
68,172031931,General disorders and administration site cond...,death,F,54,1,1
79,180927541,General disorders and administration site cond...,death,F,-1,1,1
...,...,...,...,...,...,...,...
69371,205523161,General disorders and administration site cond...,death,F,65,1,1
69443,213859832,General disorders and administration site cond...,death,F,54,1,1
69446,214714983,General disorders and administration site cond...,death,F,73,1,1
69477,222448563,General disorders and administration site cond...,death,F,-1,1,1
69540,232680071,General disorders and administration site cond...,death,F,63,1,1

In [373]:
df = pt_characteristics_stat.groupby('primaryid').agg(
    {
        'age': "max",
        'sex': "max",
        'is_serious_case': "max",
        'is_death_case': "max"
    }
)
df.sum()

age                                                           412387
sex                FFFFFFFMFFFFFFFFFFFFFFFMFMFFFFFFFFFFFFFFFFFMFF...
is_serious_case                                                11279
is_death_case                                                   3072
dtype: object

In [374]:
len(df)-11279

4046

In [376]:
## USED https://blog.51cto.com/u_16213421/9517898
import numpy as np
import scipy
df = pt_characteristics_stat.groupby('primaryid').agg(
    {
        'age': "max",
        'sex': "max",
        'is_serious_case': "max",
        'is_death_case': "max"
    }
)

df = df[df['sex'].isin(['F', 'M'])]
contingency_table = pd.crosstab(df['sex'],
                                df['is_serious_case'],
                                values = 'primaryid', aggfunc='count');

print(scipy.stats.chi2_contingency(contingency_table))
print(df.describe())
df

Chi2ContingencyResult(statistic=0.9215339694794128, pvalue=0.33707252407824384, dof=1, expected_freq=array([[ 3536.71290754, 10395.28709246],
       [   68.28709246,   200.71290754]]))
                age  is_serious_case  is_death_case
count  14201.000000     14201.000000   14201.000000
mean      28.384128         0.746145       0.207098
std       32.037812         0.435231       0.405241
min       -1.000000         0.000000       0.000000
25%       -1.000000         0.000000       0.000000
50%       -1.000000         1.000000       0.000000
75%       60.000000         1.000000       0.000000
max      102.000000         1.000000       1.000000

           age sex  is_serious_case  is_death_case
primaryid
107579258   53   F                1              1
110919089   50   F                1              0
122636552   86   F                1              0
123719355   77   F                1              1
124738054   53   F                1              0
...        ...  ..              ...            ...
236863121   43   F                0              0
236867201   63   F                0              0
236880031   80   F                1              1
236887271   -1   F                0              0
236898421   -1   F                1              0

[14201 rows x 4 columns]

In [377]:
# Age,years(median,IQR)
import numpy as np
import scipy
df = pt_characteristics_stat.groupby('primaryid').agg(
    {
        'age': "max",
        'sex': "max",
        'is_serious_case': "max",
        'is_death_case': "max"
    }
)
## 年龄>=0, 性别:F/M
df = df[df['age']>=0].reset_index()

def P25(x):
    return np.percentile(x, 25)
def P75(x):
    return np.percentile(x, 75)

p_table = pd.pivot_table(df,
                        index = ['is_serious_case',],
                        values= ['age','primaryid'],
                        aggfunc = {
                                    'age': ['median', P25, P75],
                                    'primaryid': 'count'
                                }
                         );

print('\n ------ brief of pd -------- \n')
print(df.describe())
print('\n ------ result of pivot_table -------- \n')
print(p_table.transpose())
print('\n ------ result of mannwhitneyu test--------\n')
print(scipy.stats.mannwhitneyu( df[df['is_serious_case'] == 1]['age'], df[df['is_serious_case'] == 0]['age']))

 ------ brief of pd --------

               age  is_serious_case  is_death_case
count  6978.000000      6978.000000    6978.000000
mean     60.294354         0.883921       0.263686
std      13.660199         0.320343       0.440663
min       0.000000         0.000000       0.000000
25%      50.000000         1.000000       0.000000
50%      61.000000         1.000000       0.000000
75%      70.000000         1.000000       1.000000
max     102.000000         1.000000       1.000000

 ------ result of pivot_table --------

is_serious_case       0       1
age       P25      54.0    50.0
          P75      71.0    70.0
          median   63.0    61.0
primaryid count   810.0  6168.0

 ------ result of mannwhitneyu test--------

MannwhitneyuResult(statistic=2284527.5, pvalue=7.435203840666788e-05)

In [302]:
df = pt_characteristics_stat.groupby('primaryid').agg(
    {
        'age': "max",
        'sex': "max",
        'is_serious_case': "max",
        'is_death_case': "max"
    }
)
df.describe()
df[df['age']<0]

           age sex  is_serious_case  is_death_case
primaryid
133624611   -1   F                1              0
134133742   -1   M                1              0
134762861   -1                    1              0
134764141   -1                    1              0
134765141   -1                    1              0
...        ...  ..              ...            ...
236874181   -1                    0              0
236878011   -1                    0              0
236881601   -1                    1              0
236887271   -1   F                0              0
236898421   -1   F                1              0

[8347 rows x 4 columns]

MannwhitneyuResult(statistic=2287610.5, pvalue=7.740765995032502e-05)

is_serious_case       0       1
age       P25      54.0    50.0
          P75      71.0    70.0
          median   63.0    61.0
primaryid count   811.0  6167.0

In [250]:
df.head()

           age sex  is_serious_case  is_death_case
primaryid
107579258   53   F                1              1
110919089   50   F                1              0
122636552   86   F                1              0
123719355   77   F                1              1
124738054   53   F                1              0

###  Age,Years(median,IQR)

In [379]:
print('result for Age,Years(median,IQR)')
import numpy as np
df.groupby('is_serious_case').sum()

result for Age,Years(median,IQR)

,primaryid,age,sex,is_death_case
is_serious_case,,,,
0,1352655611356311811357131911358019511361014111...,50224,FFFFFFFMFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,0
1,1075792581109190891226365521237193551247380541...,370510,FFFFFFFMFFFFFFFFFFFFFFFMFFFFFFFFFFFFFFFFFFFFFF...,1840

In [380]:
df1 = pt_characteristics_stat.groupby('primaryid').max(['age', 'is_serious_case', 'is_death_case'])
df2 = df1[df1['age']==0]
df2

           age  is_serious_case  is_death_case
primaryid
142902031    0                1              0

## PT 和 是否严重的相关性分析： 皮尔逊卡方检验

In [362]:
# Age,years(median,IQR)
import numpy as np
import scipy
df = pt_characteristics_stat.groupby(['primaryid', 'pt']).agg(
    {
        'age': "max",
        'sex': "max",
        'is_serious_case': "max",
        'is_death_case': "max",
    }
)
## 年龄>=0, 性别:F/M
## df = df[df['age']>=0].reset_index()
df = df.reset_index()
df['is_non_serious_case'] = 1 - df['is_serious_case']

df_pt_serious_chitest_data = df.groupby('pt').agg(
    {
        'is_serious_case': 'sum',
        'is_non_serious_case': 'sum',
        'is_death_case': "sum",
        'primaryid': 'count'
    }   
);

df_pt_serious_chitest_data.head()

,is_serious_case,is_non_serious_case,is_death_case,primaryid
pt,,,,
abdominal adhesions,1,0,0,1
abdominal discomfort,233,99,28,332
abdominal distension,120,18,34,138
abdominal hernia,4,0,1,4
abdominal hernia infection,1,0,0,1

In [384]:
from scipy.stats import chi2_contingency
total_serious_case = 11279
total_non_serious_case = 4046
total_case = total_serious_case+total_non_serious_case

def get_person_chitest(row):
 
    is_serious_case = row['is_serious_case']
    is_non_serious_case = row['is_non_serious_case']
    is_death_case = row['is_death_case']
    primaryid = row['primaryid']

    stat, p, dof, expected = chi2_contingency([[is_serious_case,is_non_serious_case],
                                        [total_serious_case-is_serious_case,total_non_serious_case - is_non_serious_case ]])
    
    serious_col =  f"{is_serious_case} ({is_serious_case * 100/ total_serious_case:.2f})";
    non_serious_col = f"{is_non_serious_case} ({is_non_serious_case * 100/ total_non_serious_case:.2f})";
    statistic_col = f"{stat:.3f}"
    p_value_col = '<0.001' if p <0.001 else f"{p:.3f}"

    return serious_col, non_serious_col, statistic_col, p_value_col, is_death_case
  
df_pt_serious_chitest_data[['Serious cases (n = {})'.format(total_serious_case), 'Non-serious cases (n = {})'.format(total_non_serious_case), "Statistic", "p value", "death case count"]] \
    =  df_pt_serious_chitest_data.apply(get_person_chitest, axis = 1, result_type = "expand");


df_pt_serious_chitest_data.head()

df_ror_pt_abcd_from_file = pd.read_excel('pt_ror_result.xlsx')
pt_info = pd.merge(df_ror_pt_abcd_from_file, df_pt_serious_chitest_data, how='inner', on = ['pt',], suffixes=['_ror_soc_abcd', '_chisquare'], copy=True)
pt_info.to_excel('pt_info.xlsx', index=False)